PUTBASIC "src/POLY1.bas","POLY1"
PUTBASIC "src/POLY2.bas","POLY2"
PUTFILE "src/LFISH.bin","LFISH",0
PUTFILE "src/RFISH.bin","RFISH",0
PUTFILE "src/DLFISH.bin","DLFISH",0
PUTFILE "src/DRFISH.bin","DRFISH",0
PUTFILE "src/LSHK.bin","LSHK",0
PUTFILE "src/RSHK.bin","RSHK",0
PUTFILE "src/LDIVER.bin","LDIVER",0
PUTFILE "src/RDIVER.bin","RDIVER",0
PUTTEXT "src/BOOT.txt", "!BOOT",&FFFF